```{r}
library(tidyverse)
library(leaflet)
library(ggblend)
library(patchwork)
```

## Joint visualization of the UMAP embedding
```{r}
umap <- vroom("data/single_cell_objects/eb_pflog1ppfnorm.hvg.umap_embedding.txt", col_names=c("UMAP_1", "UMAP_2"))
cm_pcs <- vroom("data/trajectory_inference/eb-cm_lineage/eb-cm_lineage.15binstrimmed_pseudotime.2pcs.tsv")
neur_pcs <- vroom("data/trajectory_inference/eb-neur_lineage/eb-neur_lineage.15binstrimmed_pseudotime.2pcs.tsv")
hep_pcs <- vroom("data/trajectory_inference/eb-hep_lineage/eb-hep_lineage.15binstrimmed_pseudotime.2pcs.tsv")
celltypes <- vroom("data/fca/eb_cellid_labels.tsv")
umap$cell <- celltypes$cell
```

Assign pseudotime to a color for each trajectory
```{r}
cm_palette <- colorBin(palette = c("#D5D5D5", "#B51700"), domain=cm_pcs$PC1)
neur_palette <- colorBin(palette = c("#D5D5D5", "#0076BA"), domain=neur_pcs$PC1)
hep_palette <- colorBin(palette = c("#D5D5D5", "#FEAE00"), domain=hep_pcs$PC1)

cm_pcs$cm_color <- cm_palette(cm_pcs$PC1)
neur_pcs$neur_color <- neur_palette(neur_pcs$PC1)
hep_pcs$hep_color <- hep_palette(hep_pcs$PC1)
```

```{r}
isolation_df <- left_join(umap, dplyr::select(cm_pcs, c(cell, cm_color)), by="cell") %>%
  left_join(dplyr::select(neur_pcs, c(cell, neur_color)), by="cell") %>%
  left_join(dplyr::select(hep_pcs, c(cell, hep_color)), by="cell")
```

We need each cell to have a single pseudotime value and trajectory (we'll arbitrarily choose a lineage for cells mapped to multiple)
```{r}
trajectories_sampled <- isolation_df %>%
  pivot_longer(cols=!c(cell, UMAP_1, UMAP_2), names_to="trajectory", values_to="pseudotime_color") %>%
  drop_na() %>%
  group_by(cell, UMAP_1, UMAP_2) %>%
  sample_n(size=1) %>%
  ungroup

pseudotime_df <- right_join(trajectories_sampled, dplyr::select(isolation_df, c(cell, UMAP_1, UMAP_2)), by=c("cell", "UMAP_1", "UMAP_2")) %>%
  replace_na(list(pseudotime_color="#E6E6E6", trajectory="none")) %>%
  mutate(trajectory=factor(trajectory, levels=c("none", "neur_color", "cm_color", "hep_color"))) %>%
  arrange(trajectory)
```


```{r fig.height=3.5, fig.width=4}
pseudotime_plot <- ggplot(pseudotime_df, aes(x=UMAP_1, y=UMAP_2, color=pseudotime_color)) +
  geom_point(data=filter(pseudotime_df, trajectory == "none"), alpha=0.2) +
  geom_point(data=filter(pseudotime_df, trajectory != "none"), size=1e-9, alpha=0.5) * (blend("lighten") + blend("multiply", alpha = 0.5)) +
  scale_color_identity() +
  theme_classic(base_size=6) +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) +
  xlab("UMAP 1") + ylab("UMAP 2")
```

## Visualization of Each Trajectory in Isolation
```{r fig.height=3, fig.width=4}
pseudo_cm_plot <- ggplot(cm_pcs, aes(x=PC1, y=PC2, color=PC1)) +
  geom_point(size = 1e-5) +
  scale_color_gradient(low="#929292", high="#B51700") +
  theme_classic(base_size=6) +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.key.size = unit(0.05, "in")) +
  xlab("") + ggtitle("Cardiomyocyte Trajectory")

pseudo_neur_plot <- ggplot(neur_pcs, aes(x=PC1, y=PC2, color=PC1)) +
  geom_point(size = 1e-5) +
  scale_color_gradient(low="#929292", high="#0076BA") +
  theme_classic(base_size=6)  +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.key.size = unit(0.05, "in")) +
  xlab("") + ggtitle("Neuronal Trajectory")

pseudo_hep_plot<- ggplot(hep_pcs, aes(x=PC1, y=PC2, color=PC1)) +
  geom_point(size = 1e-5) +
  scale_color_gradient(low="#929292", high="#FEAE00") +
  theme_classic(base_size=6)  +
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.key.size = unit(0.05, "in")) +
  xlab("Pseudotime (PC1)") + ggtitle("Hepatocyte Trajectory")
```

## Marker Gene Expression
```{r}
smoothed_markers <- vroom("/project2/gilad/jpopp/ebQTL/temp/smoothed_marker_gene_exp_cm.tsv") %>%
  pivot_longer(cols=c(NANOG, MIXL1, MESP1, GATA4, TNNT2), names_to="gene", values_to="expression") %>%
  mutate(gene=factor(gene, levels=c("NANOG", "MIXL1", "MESP1", "GATA4", "TNNT2")))

cm_palette_discrete <- colorBin(palette = c("#D5D5D5", "#B51700"), domain=seq(5))(seq(5))

marker_plot <- ggplot(smoothed_markers, aes(x=pseudotime, y=expression, color=gene)) +
  geom_line(lwd=1) +
  theme_classic(base_size=6) +
  theme(axis.ticks.x=element_blank(), axis.ticks.y=element_blank(), axis.text.x=element_blank(), axis.text.y=element_blank(), legend.key.size = unit(0.05, "in")) +
  xlab("Pseudotime") + ylab("Relative Expression") +
  labs(color="Marker Gene") +
  scale_color_manual(values=c("#929292", "#E2C4BE", "#DF8A89", "#C74B31", "#B51700"))
```


```{r fig.height=3, fig.width=9}
layout <- "
AAAABBEEE
AAAACCEEE
AAAADDEEE
"
png(filename="/project2/gilad/jpopp/ebQTL/figs/fig3/fig3_traj.png", width=1800, height=750, res=300)
pseudotime_plot + pseudo_cm_plot + pseudo_neur_plot + pseudo_hep_plot + marker_plot +
  plot_layout(design = layout)
dev.off()
```

