```{r}
library(tidyverse)
library(RColorBrewer)
```

```{r}
g <- "HCRTR2"
v <- "rs6913948"
```

## QTL Discovery
First, let's look at how the QTL was discovered. I'll first get a STRUCTURE plot to see how the topics are being used
```{r}
topic_loadings <- vroom("results/fast_topics/fasttopics_10topics_loadings.tsv")
betas <- vroom("results/cellregmap_eqtl_calling/eb_cellid/pseudobulk_tmm/basic/mash-signif.fasttopics_10topics.HCRTR2.cellregmap.betas.tsv", col_select=c("PSEUDOCELL", "BETA_GXC", "BETA_G"))
```

```{r, fig.width=8, fig.height=4}
topics_kept <- c('k1','k2', 'k4','k5','k6', 'k7', 'k8', 'k10')
structure_df <- topic_loadings %>%
  dplyr::select(all_of(c("pseudocell", topics_kept))) %>%
  inner_join(betas, by=c("pseudocell"="PSEUDOCELL")) %>%
  pivot_longer(cols=topics_kept, names_to="topic", values_to="loading") %>%
  mutate(topic=factor(topic, levels=topics_kept))

ggplot(structure_df, aes(x=BETA_GXC, y=loading, fill=topic)) +
  geom_col(width=1e-3) +
  theme_classic(base_size=35) +
  scale_fill_manual(values=brewer.pal(9, 'Set1')) +
  #theme(legend.position="none") +
  xlab(paste0("Aggregate Interacting Environment at ", v)) +
  ylab("Topic Loadings")
```

```{r}
pseudocell_exp <- vroom("data/single_cell_objects/eb_pseudocells_normalized.tsv", col_select=c(`...1`, g))
```

