```{r}
library(tidyverse)
```

```{r}
height_ldsc <- vroom("results/ldsc/baseline_geneset_GOBP-SKELETAL-SYSTEM-DEVELOPMENT_full_gtexcomb_mash-signif_annot/UKB_460K.body_HEIGHTz.results") %>%
  mutate(Category=str_extract(Category, "[^L2_0]+")) %>%
  filter(Category %in% c("GTEx", "EB")) %>%
  mutate(highlight = Category == "EB")
ggplot(height_ldsc, aes(x=factor(Category, levels=c("GTEx", "EB")), y=Enrichment)) +
  geom_errorbar(aes(ymin = Enrichment - Enrichment_std_error, ymax = Enrichment + Enrichment_std_error), position = position_dodge(width = 0.9), width = 0.1) +
  geom_point(size=5, aes(color=highlight)) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_manual(values=c("#BBBBBB", "#B51700")) +
  labs(x = "Dataset",
       y = expression(atop("Height Heritability Enrichment", "(eQTLs for Skeletal Development Genes)"))) +
  theme_classic(base_size=20) +
  theme(legend.position = "none") +
  coord_flip()
```

```{r}
scz_ldsc <- vroom("results/ldsc/baseline_geneset_GOBP-CENTRAL-NERVOUS-SYSTEM-DEVELOPMENT_full_gtexcomb_mash-signif_annot/PASS_Schizophrenia_Pardinas2018.results") %>%
  mutate(Category=str_extract(Category, "[^L2_0]+")) %>%
  filter(Category %in% c("GTEx", "EB")) %>%
  mutate(highlight = Category == "EB")
ggplot(scz_ldsc, aes(x=factor(Category, levels=c("GTEx", "EB")), y=Enrichment)) +
  geom_errorbar(aes(ymin = Enrichment - Enrichment_std_error, ymax = Enrichment + Enrichment_std_error), position = position_dodge(width = 0.9), width = 0.1) +
  geom_point(size=5, aes(color=highlight)) +
  geom_hline(yintercept=1, linetype="dashed") +
  scale_color_manual(values=c("#BBBBBB", "#B51700")) +
  labs(x = "Dataset",
       y = expression(atop("SCZ Heritability Enrichment", "(eQTLs for CNS Development Genes)"))) +
  theme_classic(base_size=20) +
  theme(legend.position = "none") +
  coord_flip()
```