```{r}
library(tidyverse)
library(RColorBrewer)
library(ggblend)
```

```{r}
g <- "PSD"
v <- "rs11191291"
```

## QTL Discovery
First, let's look at how the QTL was discovered. I'll first get a STRUCTURE plot to see how the topics are being used
```{r}
topic_loadings <- vroom("results/fast_topics/fasttopics_10topics_loadings.tsv")
betas <- vroom("results/cellregmap_eqtl_calling/eb_cellid/pseudobulk_tmm/basic/mash-signif.fasttopics_10topics.CDK5.cellregmap.betas.tsv", col_select=c("PSEUDOCELL", "BETA_GXC", "BETA_G", "EB_HGNC", "EB_VARIANT_ID"))
betas_wide <- dplyr::select(betas, c(PSEUDOCELL, BETA_GXC, EB_HGNC, EB_VARIANT_ID)) %>%
  unite(EB_QTL, EB_HGNC, EB_VARIANT_ID, sep="_") %>%
  pivot_wider(id_cols=PSEUDOCELL, names_from=EB_QTL, values_from=BETA_GXC)
betas_loadings <- left_join(betas_wide, topic_loadings, by=c("PSEUDOCELL"="pseudocell"))
```

```{r, fig.width=8, fig.height=4}
topics_kept <- c('k1','k2', 'k4','k5','k6', 'k7', 'k8', 'k10')
structure_df <- topic_loadings %>%
  dplyr::select(all_of(c("pseudocell", topics_kept))) %>%
  inner_join(betas, by=c("pseudocell"="PSEUDOCELL")) %>%
  pivot_longer(cols=topics_kept, names_to="topic", values_to="loading") %>%
  mutate(topic=factor(topic, levels=topics_kept))

ggplot(structure_df, aes(x=BETA_GXC, y=loading, fill=topic)) +
  geom_col(width=1e-3) +
  theme_classic(base_size=35) +
  scale_fill_manual(values=brewer.pal(9, 'Set1')) +
  xlab(paste0("Aggregate Interacting Environment at ", v)) +
  ylab("Topic Loadings")
```

```{r}
pseudocell_exp <- vroom("data/single_cell_objects/eb_pseudocells_normalized.tsv")
genotypes <- read.plink(bed="data/genotypes/yri_maf0.1_all.hg38.bed",
                        bim="data/genotypes/yri_maf0.1_all.hg38.bim",
                        fam="data/genotypes/yri_maf0.1_all.hg38.fam",
                        select.snps = v)
crm_genotypes_df <- tibble("donor"=rownames(genotypes$genotypes), "genotype"=as.numeric(genotypes$genotypes))

pseudocell_df <- betas_loadings %>%
  select(all_of(c("PSEUDOCELL", "CDK5_rs1549760"))) %>% 
  rename(beta_gxc = CDK5_rs1549760) %>%
  left_join(select(pseudocell_exp, c(`...1`, CDK5)), by=c("PSEUDOCELL"="...1")) %>%
  mutate(donor=str_extract(PSEUDOCELL, "[^_]+")) %>%
  left_join(crm_genotypes_df, by=c("donor")) %>%
  mutate(genotype=factor(genotype))

crm_qtl_plot <- ggplot(pseudocell_df, aes(x=beta_gxc, y=CDK5, color=genotype)) +
  geom_point(size=0.25) * (blend("lighten") + blend("multiply", alpha = 0.5)) +
  geom_smooth(method = "loess") +
  theme_classic(base_size=15)+
  scale_color_manual(labels=c("TT", "TA", "AA"), values=brewer.pal(3, "Set1")) +
  theme(axis.ticks.y=element_blank(), axis.text.y=element_blank(), axis.ticks.x=element_blank(), axis.text.x=element_blank()) +
  xlab("Aggregate Interacting Environment") +
  ylab("PSD Expression") +
  labs(color=v)
crm_qtl_plot
```

