---
title: "Epithelial cell types in EBs"
output: html_notebook
---

```{r}
library(SingleCellExperiment)
library(scater)
library(tidyverse)
library(Matrix.utils)
```


```{r}
eb_loc <- "/project2/gilad/jpopp/ebQTL/data/single_cell_objects/highpass/eb_pflog1ppfnorm.fca_hvgs.mca.sce"
load("/project2/gilad/jpopp/ebQTL/data/fca/cellid_signatures_and_hvgs.Rdata")
```

Load cell and gene embeddings, filter to epithelial celltypes
```{r}
eb <- readRDS(eb_loc)
eb$celltype[eb$celltype=="unassigned"] <- NA

# Get a list of cell types
cell.types <- unique(eb$celltype)
cell.types <- cell.types[!is.na(cell.types)]

# Pull MCA embeddings of cells and genes
cell_emb <- as_tibble(reducedDim(eb, "MCA"), rownames="cell") %>%
  left_join(as_tibble(colData(eb), rownames="cell"), by="cell") 
gene_emb <- attributes(cell_emb$MCA_1)$genesCoordinates

# Get cell type centroids
celltype_centroids <- as.matrix(aggregate.Matrix(reducedDim(eb, "MCA"), groupings=eb$celltype, fun="mean"))
```

Just get epithelial cells
```{r}
epithelial_types <- c("Acinar cells", "Bronchiolar and alveolar epithelial cells",
                      "Ciliated epithelial cells", "Ductal cells", "Goblet cells",
                      "Intestinal epithelial cells", "Parietal and chief cells",
                      "Metanephric cells", "Ureteric bud cells", "Squamous epithelial cells")

eb_epi <- eb[,eb$celltype %in% epithelial_types]
```

For PCA, subset to highly variable genes
```{r}
eb.epi.hvg <- intersect(rownames(eb_epi), hvg.fca_subsampled)
epi.pca <- prcomp(t(logcounts(eb_epi)[eb.epi.hvg,]), rank=50)
reducedDims(eb_epi) <- list(PCA=epi.pca$x)
```

Visualize PC space
```{r}
emb <- as_tibble(reducedDim(eb_epi, "PCA"), rownames="sample") %>%
  left_join(as_tibble(colData(eb_epi), rownames="sample")) 
emb_subset <- select(emb, c(PC1, PC2, celltype)) %>%
  group_by(celltype) %>%
  sample_n(200)

ggplot(emb_subset, aes(x=PC1, y=PC2)) +
  geom_point(aes(color=celltype)) 
```

```{r fig.width=6, fig.height=2}
plot_density(eb_epi, reduction="PCA", features=c("PAX6", "CPA2"))
```


Do these cell types do the same thing in the fetal cell atlas in PC space? It looks like mush
```{r}
fca_subsampled <- readRDS("/project2/gilad/jpopp/ebQTL/data/fca/counts.subsampled.mca_pca_fromhvgs.sce")
```

```{r}
fca_epi <- fca_subsampled[,fca_subsampled$celltype %in% epithelial_types]
```

```{r}
fca_epi.pca <- prcomp(t(logcounts(fca_epi)), rank=50)
reducedDims(fca_epi) <- list(PCA=fca_epi.pca$x)
```




