```{r}
library(tidyverse)
```

Look at pLI depletion for different types of QTLs
```{r}
pli <- vroom("temp/gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz") %>%
  dplyr::select(gene, pLI) %>%
  mutate(high_pLI = pLI >= 0.9) %>%
  drop_na() %>%
  distinct()
ambiguous_pLI_genes <- pli$gene[duplicated(pli$gene)]
pli <- filter(pli, !gene %in% ambiguous_pLI_genes)
```


TensorQTL
```{r}
tested_tensorqtl_genes <- unique(vroom("results/static_eqtl_followup/qtl_sets/tensorqtl/original/tensorqtl-all_variant_gene_pairs.bed")$EB_HGNC)
tensorqtl_egenes <- unique(vroom("results/static_eqtl_followup/qtl_sets/tensorqtl/original/signif_variant_gene_pairs.bed")$EB_HGNC)

random_samples_tensorqtl <- replicate(1000, sample(tested_tensorqtl_genes, length(tensorqtl_egenes)))

pli_egenes_tensorqtl <- tibble("gene"=tensorqtl_egenes) %>%
  inner_join(pli, by="gene") %>%
  summarize(n = n(), high_pLI = sum(high_pLI)) %>%
  mutate(low_pLI = n - high_pLI) %>%
  mutate(odds = high_pLI / low_pLI)
pli_background_tensorqtl <- as_tibble(random_samples_tensorqtl) %>%
  pivot_longer(everything(), names_to="group", values_to="gene") %>%
  inner_join(pli, by="gene") %>%
  group_by(group) %>%
  summarize(n = n(), high_pLI = sum(high_pLI)) %>%
  mutate(low_pLI = n - high_pLI) %>%
  mutate(odds = high_pLI / low_pLI)
or_dist_tensorqtl <- pli_egenes_tensorqtl$odds / pli_background_tensorqtl$odds
```

MASH eGenes
```{r}
tested_mash_genes <- unique(vroom("results/static_eqtl_followup/qtl_sets/mash/original/mash-all_variant_gene_pairs.bed")$EB_HGNC)
mash_egenes <- unique(vroom("results/static_eqtl_followup/qtl_sets/mash/original/mash-signif_variant_gene_pairs.bed")$EB_HGNC)

random_samples_mash <- replicate(1000, sample(tested_mash_genes, length(mash_egenes)))

pli_egenes_mash <- tibble("gene"=mash_egenes) %>%
  inner_join(pli, by="gene") %>%
  summarize(n = n(), high_pLI = sum(high_pLI)) %>%
  mutate(low_pLI = n - high_pLI) %>%
  mutate(odds = high_pLI / low_pLI)
pli_background_mash <- as_tibble(random_samples_mash) %>%
  pivot_longer(everything(), names_to="group", values_to="gene") %>%
  inner_join(pli, by="gene") %>%
  group_by(group) %>%
  summarize(n = n(), high_pLI = sum(high_pLI)) %>%
  mutate(low_pLI = n - high_pLI) %>%
  mutate(odds = high_pLI / low_pLI)
or_dist_mash <- pli_egenes_mash$odds / pli_background_mash$odds
```

Dynamic eGenes
```{r}
tested_dynamic_genes <- unique(vroom("results/static_eqtl_followup/qtl_sets/dynamic-eqtls/original/dynamic-all_variant_gene_pairs.bed")$EB_HGNC)
dynamic_egenes <- unique(vroom("results/static_eqtl_followup/qtl_sets/dynamic-eqtls/original/dynamic-signif_variant_gene_pairs.bed")$EB_HGNC)

random_samples_dynamic <- replicate(1000, sample(tested_dynamic_genes, length(dynamic_egenes)))

pli_egenes_dynamic <- tibble("gene"=dynamic_egenes) %>%
  inner_join(pli, by="gene") %>%
  summarize(n = n(), high_pLI = sum(high_pLI)) %>%
  mutate(low_pLI = n - high_pLI) %>%
  mutate(odds = high_pLI / low_pLI)
pli_background_dynamic <- as_tibble(random_samples_dynamic) %>%
  pivot_longer(everything(), names_to="group", values_to="gene") %>%
  inner_join(pli, by="gene") %>%
  group_by(group) %>%
  summarize(n = n(), high_pLI = sum(high_pLI)) %>%
  mutate(low_pLI = n - high_pLI) %>%
  mutate(odds = high_pLI / low_pLI)
or_dist_dynamic <- pli_egenes_dynamic$odds / pli_background_dynamic$odds
```

CRM eGenes
```{r}
tested_crm_genes <- unique(vroom("results/static_eqtl_followup/qtl_sets/mash/original/mash-signif_variant_gene_pairs.bed")$EB_HGNC)
crm_egenes <- unique(vroom("results/static_eqtl_followup/qtl_sets/dynamic-eqtls/crm-signif_variant_gene_pairs.bed")$EB_HGNC)

random_samples_crm <- replicate(1000, sample(tested_crm_genes, length(crm_egenes)))

pli_egenes_crm <- tibble("gene"=crm_egenes) %>%
  inner_join(pli, by="gene") %>%
  summarize(n = n(), high_pLI = sum(high_pLI)) %>%
  mutate(low_pLI = n - high_pLI) %>%
  mutate(odds = high_pLI / low_pLI)
pli_background_crm <- as_tibble(random_samples_crm) %>%
  pivot_longer(everything(), names_to="group", values_to="gene") %>%
  inner_join(pli, by="gene") %>%
  group_by(group) %>%
  summarize(n = n(), high_pLI = sum(high_pLI)) %>%
  mutate(low_pLI = n - high_pLI) %>%
  mutate(odds = high_pLI / low_pLI)
or_dist_crm <- pli_egenes_crm$odds / pli_background_crm$odds

random_samples_crm_v_mash <- replicate(1000, sample(tested_mash_genes, length(crm_egenes)))
pli_background_crm_v_mash <- as_tibble(random_samples_crm_v_mash) %>%
  pivot_longer(everything(), names_to="group", values_to="gene") %>%
  inner_join(pli, by="gene") %>%
  group_by(group) %>%
  summarize(n = n(), high_pLI = sum(high_pLI)) %>%
  mutate(low_pLI = n - high_pLI) %>%
  mutate(odds = high_pLI / low_pLI)
or_dist_crm_v_mash <- pli_egenes_crm$odds / pli_background_crm_v_mash$odds

```

```{r}
tibble("tensorqtl"=or_dist_tensorqtl, "dynamic"=or_dist_dynamic,
       "crm"=or_dist_crm_v_mash, "mash"=or_dist_mash) %>%
  pivot_longer(everything(), names_to="qtl", values_to="OR") %>%
  ggplot(aes(x=qtl, y=OR)) +
  geom_boxplot()
```

## Alternative strategy
This doesn't seem to make sense - why would CRM be so different? Maybe just because we fail
to account for the uncertainty in the discovery set? This can be addressed through a resampling scheme 
instead of just using the same set every time
```{r}
resampled_crm <- replicate(1000, sample(crm_egenes, length(crm_egenes), replace=T))
pli_egenes_crm_resampled <- as_tibble(resampled_crm) %>%
  pivot_longer(everything(), names_to="group", values_to="gene") %>%
  inner_join(pli, by="gene") %>%
  group_by(group) %>%
  summarize(n = n(), high_pLI = sum(high_pLI)) %>%
  mutate(low_pLI = n - high_pLI) %>%
  mutate(odds = high_pLI / low_pLI)
or_dist_crm_resampled <- pli_egenes_crm_resampled$odds / pli_background_crm_v_mash$odds

tibble("tensorqtl"=or_dist_tensorqtl, "dynamic"=or_dist_dynamic,
       "crm"=or_dist_crm_resampled, "mash"=or_dist_mash) %>%
  pivot_longer(everything(), names_to="qtl", values_to="OR") %>%
  ggplot(aes(x=qtl, y=OR)) +
  geom_boxplot()
```






