---
title: "Cell-ID Evaluation (EB Side)"
output: html_notebook
---

```{r}
library(tidyverse)
library(Matrix.utils)
library(fgsea)
library(susieR)
library(pathways)
library(vroom)
library(gseasusie)
```

```{r}
eb_sighits_loc <- "/project2/gilad/jpopp/ebQTL/results/static_qtl_calling/eb_cellid/pseudobulk_tmm/basic/8pcs/signif_variant_gene_pairs.tsv"
eb_sighits_overlap_loc <- "/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/8pcs/signif_variant_gene_pairs.full_gtex_overlap.bed"
gtf_loc <- "/project2/gilad/jpopp/ebQTL/data/gencode/gencode.hg38.filtered.gtf"
```

Load the genes with and without eQTL overlap in GTEx
```{r}
gtex_overlap <- vroom(eb_sighits_overlap_loc, col_names=c("CHR", "START", "STOP", "EB_ENSG", "EB_HGNC", 
                                                          "RSID", "CELLTYPE", "CHR1", "START1", 
                                                          "STOP1", "GTEX_ENSG", "GTEX_REF", "GTEX_ALT"))
eb_all <- vroom(eb_sighits_loc)

overlap_egenes <- unique(gtex_overlap$EB_HGNC)
all_egenes <- unique(eb_all$phenotype_id)
novel_egenes <- setdiff(all_egenes, overlap_egenes)
```

Wrangle GO BP gene sets
```{r}
gmt_file <- "/project2/gilad/jpopp/ebQTL/data/gene_sets/c5.go.bp.v2022.1.Hs.symbols.gmt"

gmt_lines <- readLines(gmt_file)

gmt_list <- lapply(gmt_lines, function(x) unlist(strsplit(x, "\t")))
gmt_list2 <- lapply(gmt_list, function(x) list(x[1], x[2], x[3:length(x)]))

gmt_df <- as_tibble(do.call("rbind", gmt_list2)) %>%
  mutate(across(V1:V2, unlist)) %>%
  dplyr::rename(geneset=V1, link=V2, genes=V3)

gmt_mat <- gmt_df %>%
  select(-c(link)) %>%
  unnest(genes) %>%
  filter(genes %in% all_egenes) %>%
  pivot_wider(names_from = genes, values_from = genes, values_fn = length, values_fill = 0) %>%
  column_to_rownames("geneset")

# subset to genesets with between 10 and 500 genes
valid_genesets <- (10 <= rowSums(gmt_mat)) & (rowSums(gmt_mat) < 500)
gmt_mat <- t(as.matrix(gmt_mat[which(valid_genesets),]))
```

# GSEA
### Pathway Analysis
```{r}
is_novel <- !rownames(gmt_mat) %in% overlap_egenes
logistic.fit <- gseasusie::fit_logistic_susie(X=gmt_mat, y=is_novel, L=5)
ora <- gseasusie::fit_ora(X=gmt_mat, y=is_novel)

if (!is.null(logistic.fit$sets$cs)) {
  cs <- pivot_longer(as_tibble(logistic.fit$sets$cs), everything(), names_to="component", values_to="index")
} else {
  cs <- tibble(component=character(), index=numeric())
}
```

The connective tissue development enrichment is exciting, see which cell types that came from
```{r}
connective_tissue_genes <- rownames(gmt_mat)[which(gmt_mat[,"GOBP_CONNECTIVE_TISSUE_DEVELOPMENT"]==1)]
novel_egenes_connective_tissue <- intersect(connective_tissue_genes, setdiff(all_egenes, overlap_egenes))

novel_connective_tissue_qtls <- filter(eb_all, phenotype_id %in% novel_egenes_connective_tissue)
```


