```{r}
library(tidyverse)
```

Helpers
```{r}
load_overlap <- function(fname) {
  read_tsv(fname, 
           col_names=c("CHR", "START", "END", "EB_ENSG", "EB_HGNC", "EB_VARIANT_ID", "GTEX_CHR", "GTEX_START", "GTEX_END", "GTEX_ENSG", "GTEX_REF", "GTEX_ALT"),
           col_select=c("CHR", "START", "END", "EB_ENSG", "EB_HGNC", "EB_VARIANT_ID", "GTEX_ENSG")) %>%
    filter(EB_ENSG == GTEX_ENSG)
}
```


```{r}
goblet_stomach_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Goblet-cells/8pcs/eqtl_overlap.Stomach.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()

goblet_heart_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Goblet-cells/8pcs/eqtl_overlap.Heart_Left_Ventricle.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()

goblet_brain_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Goblet-cells/8pcs/eqtl_overlap.Brain_Cortex.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()
```

```{r}
cm_stomach_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Stromal-cells/8pcs/eqtl_overlap.Stomach.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()

cm_heart_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Stromal-cells/8pcs/eqtl_overlap.Heart_Left_Ventricle.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()

cm_brain_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Stromal-cells/8pcs/eqtl_overlap.Brain_Cortex.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()
```
```{r}
stromal_stomach_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Stromal-cells/8pcs/eqtl_overlap.Stomach.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()

stromal_heart_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Stromal-cells/8pcs/eqtl_overlap.Heart_Left_Ventricle.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()

stromal_brain_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Stromal-cells/8pcs/eqtl_overlap.Brain_Cortex.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()
```

```{r}
neuron_stomach_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/CNS-neurons/8pcs/eqtl_overlap.Stomach.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()

neuron_heart_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/CNS-neurons/8pcs/eqtl_overlap.Heart_Left_Ventricle.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()
```

Now I'll try rerunning these analyses with three tissues that have similar sample sizes
```{r}
neuron_brain_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/CNS-neurons/8pcs/eqtl_overlap.Brain_Cortex.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()

neuron_liver_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/CNS-neurons/8pcs/eqtl_overlap.Liver.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()

neuron_artery_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/CNS-neurons/8pcs/eqtl_overlap.Artery_Coronary.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()
```

```{r}
cm_brain_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Cardiomyocytes/8pcs/eqtl_overlap.Brain_Cortex.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()

cm_liver_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Cardiomyocytes/8pcs/eqtl_overlap.Liver.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()

cm_artery_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Cardiomyocytes/8pcs/eqtl_overlap.Artery_Coronary.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()
```

```{r}
hep_brain_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Hepatoblasts/8pcs/eqtl_overlap.Brain_Cortex.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()

hep_liver_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Hepatoblasts/8pcs/eqtl_overlap.Liver.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()

hep_artery_overlap <- load_overlap("/project2/gilad/jpopp/ebQTL/results/static_eqtl_followup/eb_cellid/pseudobulk_tmm/basic/Hepatoblasts/8pcs/eqtl_overlap.Artery_Coronary.bed") %>%
  select(EB_VARIANT_ID, EB_ENSG) %>%
  distinct()
```

```{r, fig.height=6, fig.width=8}
tissue_levels <- c("Brain-Cortex", "Artery-Coronary", "Liver")
celltype_levels <- c("CNS-neurons", "Cardiomyocytes", "Hepatoblasts")
color_levels <- c("#0076BA", "#B51700", "#FEAE00")

tibble(celltype=rep(c("CNS-neurons", "Cardiomyocytes", "Hepatoblasts"), each=3),
       tissue=rep(c("Brain-Cortex", "Artery-Coronary", "Liver"), times=3),
       overlap=c(nrow(neuron_brain_overlap), nrow(neuron_artery_overlap), nrow(neuron_liver_overlap),
                 nrow(cm_brain_overlap), nrow(cm_artery_overlap), nrow(cm_liver_overlap),
                 nrow(hep_brain_overlap), nrow(hep_artery_overlap), nrow(hep_liver_overlap))) %>%
  mutate(celltype=factor(celltype, levels=celltype_levels)) %>%
  mutate(tissue=factor(tissue, levels=tissue_levels)) %>%
  ggplot(aes(x=tissue, y=overlap, fill=tissue)) +
  geom_bar(stat="identity") + 
  facet_grid(rows=vars(celltype), scales="free") +
  scale_fill_manual(values=color_levels) +
  theme_classic(base_size=14) +
  theme(legend.position="none")
```

```{r}
tibble(tissue=c("Brain-Cortex", "Artery-Coronary", "Liver"),
       n_eqtl=c(1062869, 721638, 629560)) %>%
  mutate(tissue=factor(tissue, levels=tissue_levels)) %>%
  ggplot(aes(x=tissue, y=n_eqtl, fill=tissue)) +
  geom_bar(stat="identity") + 
  scale_fill_manual(values=color_levels) +
  theme_classic(base_size=14) +
  theme(legend.position="none")
```

