---
title: "Test GESECA function"
output: html_document
---
##### Use the eb data of 20k cells randomly sampled
```{r setup, include=FALSE}
# load necessary packages
library(gseasusie)
library(pathways)
library(dplyr)
library(tidyverse)
library(susieR)
```

```{r}
# Load DE result 
#dfa_out <- readRDS("/project2/gilad/mli/eb_project/analysis/topicModel/topic_DE/de_genesExpressedInMoreTHan10Cells_20kCells/de_k10_20kCells.rds")$dfa_out

dfa_out <- readRDS("/project2/gilad/mli/eb_project/analysis/topicModel/topic_DE/de_pseudobulk_sampled_leiden20_wo_pilot/de_k10.rds")$dfa_out
```

## Loading genesets
Create the gene symbol and ensembl code mapping from the geneset dataset
```{r}
data("gene_sets_human")
gene_info <- gene_sets_human$gene_info
#get the mapping between Gene symbols and ensembl code
# symbol_ensembl_map <- gene_info[c("Symbol","Ensembl")] %>%
#   drop_na(Ensembl)

symbol_ensembl_map <- gene_info[c("Symbol","Ensembl")]
symbol_ensembl_map

```

```{r}
geneset <- gene_sets_human$gene_sets
```


### prepare data for susieR
```{r}
# test with topic 2

k2.dat <- data.frame(Ensembl  = symbol_ensembl_map$Ensembl[match(names(dfa_out$postmean[,3]), symbol_ensembl_map$Symbol)],
                     postmean = dfa_out$postmean[,3],
                     lfsr     = dfa_out$lfsr[,3],
                     threshold.on = dfa_out$postmean[,3],
                     beta     = dfa_out$postmean[,3])
k2.dat <- subset(k2.dat,lfsr < 0.01) %>%
  rownames_to_column(var="Symbol") %>%
  drop_na(Ensembl) %>%
  column_to_rownames(var="Ensembl")
k2.dat <- k2.dat[order(k2.dat$postmean,decreasing = TRUE),]

```


```{r}
k2.dat
```

#### Binarize the data as recommended by the Karl
```{r}
# make the geneset compatible with the software
gene_sets_human_modified <- gene_sets_human 
names(gene_sets_human_modified)[3] <- "X"

thresh = 1.5  # threshold for binarizing the data
bin.data <- gseasusie::prep_binary_data(gs=gene_sets_human_modified, k2.dat, thresh)

X <- bin.data$X
y <- bin.data$y

```

```{r}
genesets_karl <- gseasusie::load_gene_sets(c('c2', 'all_msigbd'))
```

```{r}
str(genesets_karl)
```

```{r}
str(gene_sets_human_modified)
```










