---
title: "Test GESECA function"
output: html_document
---
##### Use the eb data of 20k cells randomly sampled
```{r setup, include=FALSE}
# load necessary packages
library(fgsea)
library(pathways)
library(dplyr)
library(tidyverse)
library(susieR)
```

```{r}
# Load DE result 
dfa_out <- readRDS("/project2/gilad/mli/eb_project/analysis/topicModel/topic_DE/de_pseudobulk_sampled_leiden20_wo_pilot/de_k10.rds")$dfa_out
#str(dfa_out$postmean)
```

## Load geneset
```{r}
data("gene_sets_human")
genesets <- gene_sets_human$gene_sets

# remove all the NA rows
genesets <- genesets[!is.na(rownames(genesets)),]

#remove duplicated entries
genesets <- genesets[!duplicated(rownames(genesets)), ]

# gene information (for information purpose only)
gene_sets_human$gene_info %>%
  head()

```

#### Create the gene symbol and ensembl code mapping from the geneset dataset
```{r}
gene_info <- gene_sets_human$gene_info
#get the mapping between Gene symbols and ensembl code
# symbol_ensembl_map <- gene_info[c("Symbol","Ensembl")] %>%
#   drop_na(Ensembl)

symbol_ensembl_map <- gene_info[c("Symbol","Ensembl")]
symbol_ensembl_map <- symbol_ensembl_map %>%
  drop_na(Ensembl)

write.table(symbol_ensembl_map, file='/project2/gilad/mli/eb_project/analysis/topicModel/gene_enrichment/gene_name2ensembl.txt',sep='\t', row.names = FALSE)
```

```{r}
# read the mapping file
symbol_ensembl_map <- read.csv(file='/project2/gilad/mli/eb_project/analysis/topicModel/gene_enrichment/gene_name2ensembl.txt',sep='\t')
```


## prepare data for susieR
#### Test k2 as an example
```{r}
# test with topic 2
k2.dat <- data.frame(Ensembl  = symbol_ensembl_map$Ensembl[match(names(dfa_out$postmean[,2]), symbol_ensembl_map$Symbol) ], # gene symbol to ensembl because the gene set matrix is based on ensembl
                     postmean = dfa_out$postmean[,2],
                     lfsr     = dfa_out$lfsr[,2])

k2.dat <- subset(k2.dat,lfsr < 0.01) %>% # filter out the significantly differentially expressed genes
  rownames_to_column(var="Symbol") %>%
  drop_na(Ensembl) %>%
  column_to_rownames(var="Ensembl") %>% # make the row name as ensembl 
  filter(postmean > 1.5) %>% # select the "top" genes
  select(-c("Symbol"))

k2.dat <- k2.dat[order(k2.dat$postmean,decreasing = TRUE),] # order the genes from most highly expressed 

k2.dat <- data.matrix(k2.dat)
```

#### Modify the geneset to include only the genes in the topic gene list
```{r}
# subset gene set to include only the genes 
genesets_k2 <- genesets[rownames(genesets, do.NULL = FALSE) %in% rownames(k2.dat), ]
```

```{r}

# test the genes only in the gene sets (Ensembl)
# postmean_ensembl <- postmean[rownames(postmean) %in% c(gene_info["Symbol"]$Symbol), ]
# postmean_ensembl <- cbind(Symbol = rownames(postmean_ensembl), postmean_ensembl)
# rownames(postmean_ensembl) <- 1:nrow(postmean_ensembl)
# postmean_ensembl
# 
# test_postmean <- test_postmean %>%
#   left_join(symbol_ensembl_map, by="Symbol") %>%
#   drop_na(Ensembl) %>%
#   select(-c("Symbol")) %>%
#   column_to_rownames(var="Ensembl")

```

### Run susieR

Example with topic 2
```{r}
# Test susieR method for enrichment

X <- genesets_k2
y <- k2.dat[,"postmean"]

out <- susie(X,y,L = 10,intercept = TRUE,standardize = FALSE,
             estimate_residual_variance = TRUE,refine = FALSE,
             compute_univariate_zscore = FALSE,
             min_abs_corr = 0)
str(out)
```

```{r}
cs <- out$sets$cs
cs[[1]]

which(X[,cs[[1]]]>0)
X[,cs[[1]]]

```


```{r}
# Generate a data frame summarizing the results of the susie gene set
# enrichment analysis.

# s: susie object output; X: geneset matrix, y: postmean lfc for each gene; ntop: how many top genes to output
compile_gsea_table <- function (s, X, y, gene_set_info, ntop = 10) {

  # Initialize the output.
  out <- NULL
    
  # Get the credible sets.
  cs <- s$sets$cs

  # Add labels to some susie outputs.
  n                 <- length(s$lbf) # lbf: log-Bayes Factor for each single effect.
  names(s$lbf)      <- paste0("L",1:n)
  rownames(s$alpha) <- paste0("L",1:n)
  rownames(s$mu)    <- paste0("L",1:n)
  
  # Repeat for each CS.
  for (i in names(cs)) {
      
    # Get information about the variables (i.e., the gene sets) included in the CS.
    j <- cs[[i]]
    n <- length(j)
    x <- data.frame(CS = rep(i,n),
                    lbf = rep(s$lbf[i],n),
                    stringsAsFactors = FALSE)
    x <- cbind(x,
               data.frame(pip  = s$alpha[i,j],
                          coef = s$mu[i,j]),
               gene_set_info[j,])

    # For each gene set, extract the "top genes" (genes in the gene
    # set with the Y's that are the largest in magnitude).
    top_genes_all <- vector("character",n)
    for (k in 1:n) {
      genes <- which(X[,j[k]] > 0)
      genes <- genes[order(abs(y[genes]),decreasing = TRUE)]
      genes <- genes[seq(1,ntop)]
      # top gene as gene symbol and add the postmean lfc of that gene
      top_genes <- paste0(symbol_ensembl_map$Symbol[match(names(genes), symbol_ensembl_map$Ensembl) ]," (",round(y[genes],digits = 3),")")
      top_genes <- paste(top_genes,collapse = " ")
      top_genes_all[k] <- top_genes
      
    }
    top_genes_symbol <- symbol_ensembl_map$Symbol[match(top_genes_all, symbol_ensembl_map$Ensembl) ]
    x <- cbind(x,data.frame(top_genes = top_genes_all,
                            stringsAsFactors = FALSE))
    out <- rbind(out,x)
  }

  rownames(out) <- NULL
  return (out)
}
```

```{r}
compile_gsea_table(out, X, y, gene_sets_human$gene_set_info)
```

#### write a function
```{r}
gsea_susie_k <- function(k){
  # test with topic 2
  k.dat <- data.frame(Ensembl  = symbol_ensembl_map$Ensembl[match(names(dfa_out$postmean[,k]), symbol_ensembl_map$Symbol) ], # gene symbol to ensembl because the gene set matrix is based on ensembl
                       postmean = dfa_out$postmean[,k],
                       lfsr     = dfa_out$lfsr[,k])
  
  k.dat <- subset(k.dat,lfsr < 0.01) %>% # filter out the significantly differentially expressed genes
    rownames_to_column(var="Symbol") %>%
    drop_na(Ensembl) %>%
    column_to_rownames(var="Ensembl") %>% # make the row name as ensembl 
    filter(postmean > 1.5) %>% # select the "top" genes
    select(-c("Symbol"))
  
  k.dat <- k.dat[order(k.dat$postmean,decreasing = TRUE),] # order the genes from most highly expressed 
  
  k.dat <- data.matrix(k.dat)
  
  # subset gene set to include only the genes 
  genesets_k <- genesets[rownames(genesets, do.NULL = FALSE) %in% rownames(k.dat), ]
  
  # Test susieR method for enrichment
  
  X <- genesets_k
  y <- k.dat[,"postmean"]
  
  out <- susie(X,y,L = 10,intercept = TRUE,standardize = FALSE,
               estimate_residual_variance = TRUE,refine = FALSE,
               compute_univariate_zscore = FALSE,
               min_abs_corr = 0)
  
  compile_gsea_table(out, X, y, gene_sets_human$gene_set_info)
}
```

```{r}
gsea_susie_k(8)
```















### some junk codes
```{r}
# postmean <- dfa_out$postmean
# # subset the gene set to contain the genes only within the topic genes
# postmean_rownames_ensembl <- symbol_ensembl_map$Ensembl[match(rownames(postmean), symbol_ensembl_map$Symbol) ]
# 
# 
# postmean <- data.frame(postmean) %>%
#   rownames_to_column("Symbol") %>%
#   left_join(symbol_ensembl_map, by="Symbol") %>%
#   drop_na(Ensembl) %>%
#   select(-c("Symbol")) %>%
#   column_to_rownames(var="Ensembl")
#   # select(-c("Ensembl")) %>%
#   # column_to_rownames(var="Symbol")
# 
# postmean <- data.matrix(postmean)

#modify the geneset info to replace the row names (Ensembl) as gene symbol names
# geneset <- gene_sets_human$gene_sets
# 
# geneset_rownames_symbol <- symbol_ensembl_map$Symbol[match(rownames(geneset), c(symbol_ensembl_map$Ensembl))]
# rownames(geneset) <- geneset_rownames_symbol

```

